### ISSUE TITLE
`:app` unit test source set does not compile on `main` (two `FakeTonexController`s missing `restoreFootswitches()`)

### ISSUE THREAD

**Issue by wiz0floyd** [wiz0floyd/Tonex-OTG#58]
Found while establishing a clean pre-review baseline for S21 (#26) / S22 (#27) — this is **pre-existing breakage on `main`**, not caused by either of those branches.

## Symptom

At `main` = `ae9e83d` (S20 probe work merged via #57), with a clean tree and `sdk.dir` set:

```
./gradlew :app:testDebugUnitTest
```

fails at `:app:compileDebugUnitTestKotlin`:

```
e: .../app/src/test/kotlin/dev/tonexotg/app/ui/screens/parameters/FakeTonexController.kt:29:1
   Class 'FakeTonexController' is not abstract and does not implement abstract member:
   suspend fun restoreFootswitches(): TonexResult<Unit>
e: .../app/src/test/kotlin/dev/tonexotg/app/ui/screens/presets/FakeTonexController.kt:29:1
   Class 'FakeTonexController' is not abstract and does not implement abstract member:
   suspend fun restoreFootswitches(): TonexResult<Unit>
```

The **entire `:app` unit test source set** therefore does not compile, so **no `:app` test has run since this landed** — not just the two affected files' tests.

## Verified scope

- `:protocol:test` — **green** (`./gradlew :protocol:test --offline`, passes with no Android SDK involvement, per #15's standing criterion).
- `:app:compileDebugKotlin` (production sources) — **green**. Only the test source set is broken.
- Three `FakeTonexController` copies exist in `:app`'s tests; only `ui/screens/connection/FakeTonexController.kt` implements `restoreFootswitches()`.

## Cause

A semantic merge conflict, not a textual one, which is why neither PR showed a conflict:

- `8430893` — S16 preset list screen (#55), merged **first**, adds/edits `ui/screens/presets/FakeTonexController.kt`.
- `5742106` — S23 footswitch restore, protocol layer (#56), merged **second**, adds `restoreFootswitches()` to the `TonexController` interface and updates only `ui/screens/connection/FakeTonexController.kt`.

`git merge-base --is-ancestor 5742106 8430893` → false, confirming that ordering. #56 updated the fakes that existed at *its* branch point; the ones on the other in-flight branch were never revisited after the merge.

## Fix

Add to both `ui/screens/parameters/FakeTonexController.kt` and `ui/screens/presets/FakeTonexController.kt`, matching whatever the connection fake already does:

```kotlin
override suspend fun restoreFootswitches(): TonexResult<Unit> = TonexResult.Success(Unit)
```

…then actually run `./gradlew :app:testDebugUnitTest` to confirm the rest of the suite is green, since it has not executed since #56.

## Worth considering separately

Three near-duplicate `FakeTonexController` implementations is exactly the shape that guarantees this recurs on the next interface addition. Consolidating them into one shared test fake (or making the base one `open`/abstract) would make the compiler catch this once instead of three times — and only two of the three got caught here.

Also, nothing in this repo currently runs `:app:testDebugUnitTest` automatically; that is why a fully red test source set sat on `main` unnoticed across a merge. A minimal CI check (or a `SessionStart` hook) that builds both modules' test source sets would have surfaced it at #56.

**Comment by wiz0floyd** [comment]
Added the missing `restoreFootswitches()` override to the two `FakeTonexController` test doubles in `app/src/test/kotlin/dev/tonexotg/app/ui/screens/parameters/` and `app/src/test/kotlin/dev/tonexotg/app/ui/screens/presets/`. Both now return `TonexResult.Success(Unit)`, mirroring the existing implementation in the connection test double.

`:app:testDebugUnitTest` now compiles and passes successfully.

---
_Generated by [Claude Code](https://claude.ai/code)_
